name: debug-dns

on:
  workflow_dispatch:

jobs:
  dns:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_SCANNER_OPTS: "-Djava.net.preferIPv4Stack=true"
          SONAR_HOST: "http://10.158.248.153:9000"
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.sources=src
            -Dsonar.host.url=${{ env.SONAR_HOST }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}


